
- name: Check system uptime
  hosts: all
  gather_facts: no
  become: false

  tasks:
    - name: Run uptime command
      ansible.builtin.command: uptime
      register: uptime_output

    - name: Show uptime
      ansible.builtin.debug:
        msg: "{{ uptime_output.stdout }}"
