
- name: Check system uptime on controller
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Run uptime command via PATH
      ansible.builtin.shell: "uptime"
      register: uptime_output
      changed_when: false

    - name: Show uptime
      ansible.builtin.debug:
        msg: "{{ uptime_output.stdout }}"
