- name: Check system uptime
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Run uptime command
      shell: /usr/bin/uptime
      register: uptime_output

    - name: Show uptime
      debug:
        msg: "{{ uptime_output.stdout }}"
