---
- name: Drop cache in Linux
  hosts: all
  become: yes  # This ensures the task is run as root
  tasks:
    - name: Flush filesystem buffers
      command: sync

    - name: Drop pagecache, dentries, and inodes
      command: echo 3 > /proc/sys/vm/drop_caches
      args:
        creates: /proc/sys/vm/drop_caches
