- name: Create a test file
  hosts: all
  become: yes
  tasks:
    - name: Create a file in /tmp
      ansible.builtin.file:
        path: /tmp/test_awx_file.txt
        state: touch
        mode: '0644'
