---
- name: Log high CPU usage on localhost
  hosts: localhost
  become: yes
  connection: local
  tasks:

    - name: Find top 5 CPU consuming processes
      shell: "ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head -n 6"
      register: cpu_processes

    - name: Save CPU usage info to log file
      copy:
        content: "{{ cpu_processes.stdout }}"
        dest: "/var/log/high_cpu_processes.log"
        mode: '0644'

    - name: Print top CPU consuming processes
      debug:
        msg: "{{ cpu_processes.stdout_lines }}"
