---
- name: Check Machine Uptime
  hosts: localhost
  gather_facts: no  # No need to gather all facts if you only need uptime
  tasks:
    - name: Get system uptime
      command: uptime -p  # Get a human-readable uptime
      register: uptime_output

    - name: Show uptime
      debug:
        msg: "The system uptime is: {{ uptime_output.stdout }}"
